### ISSUE TITLE
Checking credentials exits if upstream issues a 500

### ISSUE THREAD

**Issue by grahamc** [packethost/prometheus-packet-sd#2]
The Packet API is issuing 500's right now, which is also coinciding with experimenting with the prometheus-packet-sd. On startup I get these logs:

```
Sep 26 19:52:31 eris systemd[1]: Started prometheus-packet-sd.service.
Sep 26 19:52:32 eris prometheus-packet-sd[13026]: failed to check Packet credentials: GET https://api.packet.net/projects?: 500  Internal Server Error
Sep 26 19:52:32 eris systemd[1]: prometheus-packet-sd.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 19:52:32 eris systemd[1]: prometheus-packet-sd.service: Failed with result 'exit-code'.
```

I think if this check fails with a 500 it should continue checking until it gets a non-500 error.

**Comment by t0mk** [comment]
hi @grahamc, thanks for reporting. I will take a look on this and #3 tomorrow.

**Comment by t0mk** [comment]
@grahamc, I added a `packet.startcheck` argument. If set, it will check the API on startup. It's on by default. You can disable it as:
```
PACKET_AUTH_TOKEN="aa" ./prometheus-packet-sd --no-startcheck
```
fixed in https://github.com/packethost/prometheus-packet-sd/commit/cc9de505421469f15c14d8fbea7b8de303b1f486
