### ISSUE TITLE
Writes to a temp file next to the output file, even if it doesn't have permission

### ISSUE THREAD

**Issue by grahamc** [packethost/prometheus-packet-sd#4]
I'm seeing errors like this:

```
Sep 26 20:17:14 eris prometheus-packet-sd[13088]: ts=2019-09-26T20:17:14.461437157Z caller=log.go:124 level=error component=sd-adapter err="open /var/lib/sd-adapter337125685: permission denied"
```

I have asked it to write to `/var/lib/packet-sd.json`. It doesn't have permission to write to `/var/lib/`, just that specific .json file. I wonder if it would be easy to make it write to TMP/TMPDIR instead?

**Comment by t0mk** [comment]
fixed in https://github.com/packethost/prometheus-packet-sd/commit/9982edda5c9770f853e3e363da594064e09ed2a5

now it will write to default OS tempdir, whatever it is on your system. It can be also set by envvar $TMPDIR.
