### ISSUE TITLE
More nice-to-have labels

### ISSUE THREAD

**Issue by grahamc** [packethost/prometheus-packet-sd#6]
It would be nice to a few more labels exportable:

 - full device UUID (for scaling where many machines are named the same thing)
 - switch ID (for partitioning networking problems)

relatedly, is billing_cycle basically if it is hourly/reserved/spot?

**Comment by t0mk** [comment]
hey @grahamc isn't the device ID already under `device_id` label?

I'll take a look on the switch ID.

**Comment by grahamc** [comment]
Nice catch. I updated the readme to reflect that: https://github.com/packethost/prometheus-packet-sd/pull/8

**Comment by t0mk** [comment]
thanks!

**Comment by t0mk** [comment]
The billing cycle is just copied from the Packet device resource, so I think it's exactly that.

**Comment by grahamc** [comment]
Thank you!
